# Generated by Django 5.1 on 2024-08-20 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networknode',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Задолженность, руб'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='house_number',
            field=models.CharField(max_length=10, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='level',
            field=models.IntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], verbose_name='Уровень узла'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='electronics_store.networknode', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=255, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='network_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='electronics_store.networknode', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateField(verbose_name='Дата выхода продукта'),
        ),
    ]
